# Is the GM of cold- vs warm-adapted populations similar in the wild?
```{r knitr_options_wild, include=FALSE}
knitr::opts_chunk$set(fig.width=10, fig.height=7, fig.fullwidth=TRUE,
fig.path='Figures/', warning=FALSE,
message=FALSE)
set.seed(2802)
```
```{r load_data_wild}
load("data/data_03122025.Rdata")
load("data/objects_03122025.Rdata")
load("data/alpha_16092025.Rdata")
load("data/beta_16092025.Rdata")
```

## Shared and unique MAGs
```{r chart1, comment="", message=FALSE, warning=FALSE}
locationcolors=c('#c4d7d1','#e08683')
subset_meta <- sample_metadata %>%
  filter(time_point=="Wild")

genome_counts_rel_fil<- genome_counts_filt %>%
  select(one_of(c("genome", subset_meta$Tube_code))) %>%
  filter(rowSums(across(where(is.numeric), ~ . != 0)) > 0) %>%
  select(genome, where( ~ is.numeric(.) && sum(.) > 0)) %>%
  column_to_rownames(., "genome")
  
genome_counts_rel_pa=1*(genome_counts_rel_fil>0)
table_upset_analysis_cont=t(aggregate(t(genome_counts_rel_pa),by=list(subset_meta$Population),FUN=sum)[,-1])
colnames(table_upset_analysis_cont)=levels(as.factor(subset_meta$Population))
table_upset_analysis=(table_upset_analysis_cont>0)*1
table_upset_analysis=data.frame(table_upset_analysis)
table_upset_analysis=apply(table_upset_analysis,2,as.integer)
rownames(table_upset_analysis) <- rownames(genome_counts_rel_pa)

upset(as.data.frame(table_upset_analysis),
  keep.order = T,
  sets = rev(c("Cold","Warm")),
  sets.bar.color= rev(locationcolors),
  mb.ratio = c(0.55, 0.45), order.by = "freq")
```

## Shapiro test
```{r shapiro_wild, comment="", message=FALSE, warning=FALSE,}
alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == Tube_code)) %>%
  filter(time_point == "Wild") %>% 
  filter(metric=="richness") %>% 
  summarize(shapiro_p_value = shapiro.test(value)$p.value) %>%
  pull(shapiro_p_value)

alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == Tube_code)) %>%
  filter(time_point == "Wild") %>% 
  filter(metric=="neutral") %>% 
  summarize(shapiro_p_value = shapiro.test(value)$p.value) %>%
  pull(shapiro_p_value)

alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == Tube_code)) %>%
  filter(time_point == "Wild") %>% 
  filter(metric=="phylogenetic") %>% 
  summarize(shapiro_p_value = shapiro.test(value)$p.value) %>%
  pull(shapiro_p_value)
```

## Alpha diversity

```{r alpha_div_plot_1_wild, comment="", message=FALSE, warning=FALSE, fig.height=4, fig.width=10, fig.fullwidth=TRUE}
alpha_div %>%
  pivot_longer(-sample, names_to = "metric", values_to = "value") %>%
  left_join(., sample_metadata, by = join_by(sample == Tube_code)) %>%
  filter(time_point=="Wild") %>%
  mutate(metric=factor(metric,levels=c("richness","neutral","phylogenetic"))) %>%
      ggplot(aes(y = value, x = species, group=species, color=species, fill=species)) +
      geom_boxplot(outlier.shape = NA) +
      geom_jitter(alpha=0.5) +
      scale_color_manual(name="species",
          breaks=c("Podarcis_muralis","Podarcis_liolepis"),
          labels=c("Podarcis muralis","Podarcis liolepis"),
          values=c('#008080', "#d57d2c")) +
      scale_fill_manual(name="species",
          breaks=c("Podarcis_muralis","Podarcis_liolepis"),
          labels=c("Podarcis muralis","Podarcis liolepis"),
          values=c('#00808050', "#d57d2c50")) +
      facet_wrap(. ~ metric,scales = "free") +
      coord_cartesian(xlim = c(1, NA)) +
      stat_compare_means(method="t.test",size=3, label.x=.58) +
      theme_classic() +
        theme(
    strip.background = element_blank(),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size=10),
    axis.text.x = element_blank(),
    # Increase plot size
    plot.title = element_text(size = 10),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 8)
      ) +
  ylab("Alpha diversity")
```

## Beta diversity

***Number of samples used***
```{r beta_div_neutral_wild_samples, results = TRUE, message=FALSE, warning=FALSE, comments=FALSE}
samples_to_keep <- sample_metadata %>%
  filter(time_point == "Wild") %>% 
  select(Tube_code) %>% 
  pull()
subset_meta <- sample_metadata %>%
  filter(time_point == "Wild")

length(samples_to_keep)
```

***Richness***
```{r beta_richness_permanova_1, warning=FALSE, comments="", message=FALSE}
richness <- as.matrix(beta_q0n$S)
richness <- as.dist(richness[rownames(richness) %in% samples_to_keep,
               colnames(richness) %in% samples_to_keep])
betadisper(richness, subset_meta$species) %>% permutest(., pairwise = TRUE)
```

```{r beta_richness_permanova, warning=FALSE, comments="", message=FALSE, results=TRUE}
adonis2(richness ~ species,
        data = subset_meta %>% arrange(match(Tube_code,labels(richness))),
        permutations = 999) %>%
        broom::tidy() %>%
        tt()
```

***Neutral***
```{r beta_neutral_permanova_1, warning=FALSE, comments="", message=FALSE}
neutral <- as.matrix(beta_q1n$S)
neutral <- as.dist(neutral[rownames(neutral) %in% samples_to_keep,
               colnames(neutral) %in% samples_to_keep])
betadisper(neutral, subset_meta$species) %>% permutest(., pairwise = TRUE)
```

```{r beta_neutral_permanova, warning=FALSE, comments="", message=FALSE, results=TRUE}
adonis2(neutral ~ species,
        data = subset_meta %>% arrange(match(Tube_code,labels(neutral))),
        permutations = 999) %>%
        broom::tidy() %>%
        tt()
```

***Phylogenetic***
```{r beta_phylo_permanova_1, warning=FALSE, comments="", message=FALSE}
phylo <- as.matrix(beta_q1p$S)
phylo <- as.dist(phylo[rownames(phylo) %in% samples_to_keep,
               colnames(phylo) %in% samples_to_keep])
betadisper(phylo, subset_meta$species) %>% permutest(., pairwise = TRUE)
```

```{r beta_phylo_permanova, warning=FALSE, comments="", message=FALSE, results=TRUE}
adonis2(phylo ~ species,
        data = subset_meta %>% arrange(match(Tube_code,labels(phylo))),
        permutations = 999) %>%
        broom::tidy() %>%
        tt()
```

***NMDS***
```{r beta_neutral_nmds, comments="", warning=FALSE, message=FALSE, results="hide"}
richness %>%
				metaMDS(.,trymax = 500, k=2, verbosity=FALSE, trace=FALSE) %>%
				vegan::scores() %>%
				as_tibble(., rownames = "sample") %>%
				left_join(subset_meta, by = join_by(sample == Tube_code)) %>%
			group_by(species) %>%
			mutate(x_cen = mean(NMDS1, na.rm = TRUE)) %>%
			mutate(y_cen = mean(NMDS2, na.rm = TRUE)) %>%
			ungroup() %>%
			ggplot(., aes(x=NMDS1,y=NMDS2, color=species, shape=type)) +
				scale_color_manual(name="species",
                    breaks=c("Podarcis_muralis","Podarcis_liolepis"),
          labels=c("Podarcis muralis","Podarcis liolepis"),
                    values=c('#008080',"#d57d2c")) +
        scale_shape_manual(name="Type",
                           breaks=c("Cold_control", "Warm_control", "Cold-intervention"),
                           labels=c("Cold-control", "Warm-control", "Cold-intervention"),
                         values=c("circle","square","triangle")) +
				geom_point(size=2) +
				geom_segment(aes(x=x_cen, y=y_cen, xend=NMDS1, yend=NMDS2), alpha=0.2) +
        labs(y = "NMDS2", x="NMDS1 \n Richness beta diversity") +
				theme_classic() +
				theme(legend.position="none")

neutral %>%
				metaMDS(.,trymax = 500, k=2, verbosity=FALSE, trace=FALSE) %>%
				vegan::scores() %>%
				as_tibble(., rownames = "sample") %>%
				left_join(subset_meta, by = join_by(sample == Tube_code))%>%
			group_by(species) %>%
			mutate(x_cen = mean(NMDS1, na.rm = TRUE)) %>%
			mutate(y_cen = mean(NMDS2, na.rm = TRUE)) %>%
			ungroup() %>%
			ggplot(., aes(x=NMDS1,y=NMDS2, color=species, shape=type)) +
				scale_color_manual(name="species",
                    breaks=c("Podarcis_muralis","Podarcis_liolepis"),
          labels=c("Podarcis muralis","Podarcis liolepis"),
                    values=c('#008080',"#d57d2c")) +
        scale_shape_manual(name="Type",
                           breaks=c("Cold_control", "Warm_control", "Cold-intervention"),
                           labels=c("Cold-control", "Warm-control", "Cold-intervention"),
                         values=c("circle","square","triangle")) +
				geom_point(size=2) +
				geom_segment(aes(x=x_cen, y=y_cen, xend=NMDS1, yend=NMDS2), alpha=0.2) +
        labs(y = "NMDS2", x="NMDS1 \n Neutral beta diversity") +
				theme_classic() +
				theme(legend.position="none")

phylo %>%
  metaMDS(.,trymax = 500, k=2, verbosity=FALSE, trace=FALSE) %>%
  vegan::scores() %>%
  as_tibble(., rownames = "sample") %>%
  left_join(subset_meta, by = join_by(sample == Tube_code)) %>%
  group_by(species) %>% 
  mutate(x_cen = mean(NMDS1, na.rm = TRUE)) %>%
  mutate(y_cen = mean(NMDS2, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(., aes(x=NMDS1,y=NMDS2, color=species, shape=type)) +
  scale_color_manual(name="species",
                    breaks=c("Podarcis_muralis","Podarcis_liolepis"),
                    labels=c("Podarcis muralis","Podarcis liolepis"),
                    values=c('#008080',"#d57d2c")) +
  scale_shape_manual(name="Type",
                           breaks=c("Cold_control", "Warm_control", "Cold-intervention"),
                           labels=c("Cold-control", "Warm-control", "Cold-intervention"),
                         values=c("circle","square","triangle")) +
  geom_point(size=2) +
  geom_segment(aes(x=x_cen, y=y_cen, xend=NMDS1, yend=NMDS2), alpha=0.2) +
  labs(y = element_blank (), x = "NMDS1 \n Phylogenetic beta diversity") +
  theme_classic() +
  theme(legend.position = "none") 
```

## Functional capacity
### Metabolic capacity index at functional level

```{r gitfs_elements_wild, warning=FALSE, comments="", message=FALSE}
GIFTs_functions_community %>%
  rowMeans() %>%
  as_tibble(., rownames = "sample") %>%
  left_join(sample_metadata, by = join_by(sample == Tube_code)) %>%
  filter(time_point == "Wild") %>%
  group_by(species) %>%
  summarise(MCI = mean(value), sd = sd(value))
```
```{r gitfs_functional_wild_3, warning=FALSE, comments="", message=FALSE}
MCI_element_wild <- GIFTs_functions_community %>%
  rowMeans() %>%
  as_tibble(., rownames = "sample") %>%
  left_join(sample_metadata, by = join_by(sample == Tube_code)) %>%
  filter(time_point == "Wild")

shapiro.test(MCI_element_wild$value) #normality test
var.test(value ~ species, data = MCI_element_wild)
t.test(value ~ species, data = MCI_element_wild, var.equal = TRUE)
```

### Differences in functional pathways
```{r comunity_elem, comment="", message=FALSE, warning=FALSE}
element_gift_wild <- element_gift %>%
  filter(time_point == "Wild") %>%
  select(-time_point, -type) %>%
  filter(rowSums(across(where(is.numeric), ~ . != 0)) > 0) %>%
  select(Tube_code, where( ~ is.numeric(.) && sum(.) > 0)) %>%
  left_join(sample_metadata[c(1, 4)], by = "Tube_code")
```

```{r commun_wilcox_elem_wild, comment="", message=FALSE, warning=FALSE}
significant_elements_wild <- element_gift_wild %>%
  pivot_longer(-c(Tube_code, Population),
               names_to = "trait",
               values_to = "value") %>%
  group_by(trait) %>%
  summarise(p_value = wilcox.test(value ~ Population)$p.value) %>%
  mutate(p_adjust = p.adjust(p_value, method = "BH")) %>%
  filter(p_adjust < 0.05) %>%
  rownames_to_column(., "Elements")  %>%
  select(-Elements)

element_gift_sig_wild <- element_gift_wild %>%
  select(Tube_code, all_of(intersect(
    significant_elements_wild$trait,
    colnames(element_gift_wild)
  ))) %>%
  left_join(., sample_metadata[c(1, 4)], by = join_by(Tube_code == Tube_code))

difference_table_wild <- element_gift_sig_wild %>%
  select(-Tube_code) %>%
  group_by(Population) %>%
  summarise(across(everything(), mean)) %>%
  t() %>%
  row_to_names(row_number = 1) %>%
  as.data.frame() %>%
  mutate_if(is.character, as.numeric) %>%
  rownames_to_column(., "Elements") %>%
  left_join(., uniqueGIFT_db[c(1, 3, 4)], by = join_by(Elements == Code_element)) %>%
  arrange(Function) %>%
  mutate(Difference = Cold - Warm) %>%
  mutate(group_color = ifelse(Difference < 0, "Warm", "Cold")) 
```

```{r commun_wilcox_elem_plot_wild, comment="", message=FALSE, warning=FALSE, fig.height=6, fig.width=12, fig.fullwidth=TRUE}
difference_table_wild %>%
  ggplot(aes(x = forcats::fct_reorder(Function, Difference),y = Difference,fill = group_color)) +
  geom_col() +
  scale_fill_manual(values = c('#008080', "#d57d2c")) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  theme(
    axis.text = element_text(size = 10),
    axis.title = element_text(size = 12),
    legend.position = "right",
    legend.title = element_blank(),
    panel.background = element_blank(),
    panel.grid.major = element_line(
      size = 0.15,
      linetype = 'solid',
      colour = "grey"
    )
  ) +
  xlab("Function") +
  ylab("Mean difference")
```
