
# Antimicrobial resistance

```{r load_genome_annotations_amr, warning=FALSE, comments="", message=FALSE}
genome_annotations_amr <- read_tsv("data/gene_annotations_amr.tsv.xz") %>%
    filter(resistance_type=="AMR")

genome_taxonomy_amr <- read_tsv("data/genome_taxonomy_amr.tsv")
```

## Add genome column to the annotations dataframe

```{r genome_annotations_amr, warning=FALSE, comments="", message=FALSE}
genome_annotations_amr <- genome_annotations_amr %>%
  mutate(genome = sub("@.*", "", gene))
```

## Link metadata information to the genomes

```{r genome_annotations_amr_metadata, warning=FALSE, comments="", message=FALSE}
gene_amr_metadata<-genome_annotations_amr %>%
    left_join(merged_data[c(1, 15, 16,23)], by="genome") %>%
    filter(time_point=="Wild") %>%
    left_join(genome_metadata[c(1, 3,6,7,8)], by = "genome")
```

## AMR diversity

***Amount of AMR genes per species***

```{r genome_annotations_amr_species, warning=FALSE, comments="", message=FALSE}
gene_amr_metadata %>%
  count(species.y, individual) %>%   # count AMR per individual
  group_by(species.y) %>%
  summarise(
    mean_AMR = mean(n),
    sd_AMR = sd(n),
    n_individuals = n()
  )%>%
tt()
```

```{r genome_annotations_amr_species_test, warning=FALSE, comments="", message=FALSE}
amr_indiv <- gene_amr_metadata %>%
  count(species.y, individual)

kruskal.test(n ~ species.y, data = amr_indiv)
```

```{r genome_annotations_amr_plot, warning=FALSE, comments="", message=FALSE}
gene_amr_metadata %>%
  count(genome, phylum, species, resistance_target, species.y) %>%
  group_by(species.y) %>%
  ggplot(aes(y = n, x = species.y, color=species.y, fill=species.y)) +
      geom_col() +
   scale_color_manual(name="Species",
          breaks=c("Podarcis_muralis","Podarcis_liolepis"),
          labels=c("Podarcis muralis","Podarcis liolepis"),
          values=c('#008080', "#d57d2c"))+
  scale_fill_manual(name="Species",
          breaks=c("Podarcis_muralis","Podarcis_liolepis"),
          labels=c("Podarcis muralis","Podarcis liolepis"),
          values=c('#00808050', "#d57d2c50"))+
  theme_classic() +
  theme(
    strip.background = element_blank(),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size=10),
    axis.text.x = element_blank(),
    # Increase plot size
    plot.title = element_text(size = 10),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 8)
      ) +
  ylab("Nº of AMR genes") 
```

***Type of AMR genes per species***

```{r genome_annotations_amr_plot_type, warning=FALSE, comments="", message=FALSE, fig.height=17, fig.width=17, fig.fullwidth=TRUE}
gene_amr_metadata %>%
  count(genome, phylum, species, resistance_target, species.y) %>%
  group_by(species.y) %>%
  ggplot(aes(y = n, x = species.y, color=resistance_target, fill=resistance_target)) +
      geom_col(position = "stack") +
  theme_classic() +
  theme(
    strip.background = element_blank(),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size=10),
    axis.text.x = element_blank(),
    # Increase plot size
    plot.title = element_text(size = 10),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 8),
    legend.position = "bottom"
      ) +
  guides(fill = guide_legend(nrow = 3, byrow = TRUE)) +
  ylab("Nº of AMR genes") 
```

***Nº of AMR genes per phylum***

```{r genome_annotations_amr_plot_phylum, warning=FALSE, comments="", message=FALSE}
gene_amr_metadata %>%
  count(genome, phylum, species, resistance_target, species.y) %>%
  group_by(phylum) %>%
  ggplot(aes(y = n, x = phylum, color=species.y, fill=species.y)) +
      geom_col() +
   scale_color_manual(name="Species",
          breaks=c("Podarcis_muralis","Podarcis_liolepis"),
          labels=c("Podarcis muralis","Podarcis liolepis"),
          values=c('#008080', "#d57d2c"))+
  scale_fill_manual(name="Species",
          breaks=c("Podarcis_muralis","Podarcis_liolepis"),
          labels=c("Podarcis muralis","Podarcis liolepis"),
          values=c('#00808050', "#d57d2c50"))+
  theme_classic() +
  theme(
    strip.background = element_blank(),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.title.x = element_text(size=10),
    axis.title.y = element_text(size=10),
    axis.text.x = element_text(angle=45, hjust=1, vjust=1),
    # Increase plot size
    plot.title = element_text(size = 10),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 8)
      ) +
  ylab("Nº of AMR genes") +
  xlab("Phylum")
```

***Nº of AMR genes per genome***

```{r genome_annotations_amr_plot_phylum_genome, warning=FALSE, comments="", message=FALSE}
gene_amr_metadata %>%
  count(genome, phylum, species, resistance_target, species.y) %>%
  group_by(phylum) %>%
  ggplot(aes(y = n, x = genome, color=phylum, fill=phylum)) +
      geom_col()+
  theme_classic() +
  theme(
    strip.background = element_blank(),
    panel.grid.minor.x = element_line(size = .1, color = "grey"),
    axis.title.x = element_text(size=10),
    axis.title.y = element_text(size=10),
    axis.text.x = element_blank(),
    # Increase plot size
    plot.title = element_text(size = 10),
    axis.text = element_text(size = 8),
    axis.title = element_text(size = 8)
      ) +
  ylab("Nº of AMR genes") +
  xlab("Genome")
```
